# Generated by Django 2.2.19 on 2021-04-07 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import separatedvaluesfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование группы')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Муниципальный объект', 'Муниципальный объект'), ('Орган власти', 'Орган власти')], max_length=20, verbose_name='Кем является')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электроная почта')),
                ('phone_number', models.TextField(blank=True, max_length=25, verbose_name='Телефонный номер')),
                ('role', models.CharField(blank=True, choices=[('Поручитель отчётности', 'Поручитель отчётности'), ('Субъект отчётности', 'Субъект отчётности'), ('Администратор', 'Администратор')], max_length=30, verbose_name='Роль')),
                ('organisation', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_application.Organisation', verbose_name='Организация')),
                ('user', models.OneToOneField(default='default user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Наименование отчёта')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнего обновления')),
                ('status', models.CharField(choices=[('Сформирован', 'Сформирован'), ('Рассматривается', 'Рассматривается'), ('Доработать', 'Доработать'), ('Новый', 'Новый')], max_length=20, verbose_name='Статус')),
                ('count_col', models.IntegerField(default='', verbose_name='Кол-во колонок')),
                ('count_row', models.IntegerField(default='', verbose_name='Кол-во колонок')),
                ('context', separatedvaluesfield.models.SeparatedValuesField(max_length=10000, null=True, verbose_name='Содержание таблицы')),
                ('top_names', separatedvaluesfield.models.SeparatedValuesField(blank=True, max_length=1000, null=True, verbose_name='Имена заголовков таблицы')),
                ('message', models.TextField(default='', max_length=3000, verbose_name='Приложенное сообщение')),
                ('message_help', models.TextField(blank=True, default='', max_length=1000, verbose_name='Сообщение для помощи')),
                ('typeOne', models.BooleanField(default=True, verbose_name='Одинарное значение?')),
                ('string_informations', models.TextField(default='', max_length=5000, verbose_name='Информация по строкам')),
                ('finished_create', models.BooleanField(default=False, verbose_name='Форма создана?')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_application.GroupOfReports')),
                ('organisation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_application.Organisation')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
