# Generated by Django 2.2.13 on 2020-08-26 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationOfReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReportStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электроная почта')),
                ('phone_number', models.TextField(blank=True, max_length=25, verbose_name='Телефонный номер')),
                ('organisation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_application.OrganisationOfReport', verbose_name='Организация')),
                ('user', models.OneToOneField(default='default user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('context', models.TextField(blank=True, default='', max_length=3000)),
                ('columns', models.IntegerField(default='')),
                ('top_names', models.TextField(blank=True, default='')),
                ('message', models.TextField(default='', max_length=600)),
                ('message_help', models.TextField(blank=True, default='', max_length=600, verbose_name='Сообщение для помощи')),
                ('organisation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_application.OrganisationOfReport')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_application.ReportStatus', verbose_name='Статус')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
