# Generated by Django 2.2.19 on 2021-04-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='count_row',
            field=models.IntegerField(default='', verbose_name='Кол-во строк'),
        ),
    ]
