# Generated by Django 2.2.13 on 2020-10-22 07:24

from django.db import migrations
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='context',
            field=separatedvaluesfield.models.SeparatedValuesField(max_length=3000, verbose_name='Содержание таблицы'),
        ),
        migrations.AlterField(
            model_name='report',
            name='top_names',
            field=separatedvaluesfield.models.SeparatedValuesField(blank=True, max_length=1000, null=True, verbose_name='Имена заголовков таблицы'),
        ),
    ]
