# Generated by Django 2.2.13 on 2020-09-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleUser',
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='columns',
            field=models.IntegerField(default='', verbose_name='Кол-во колонок'),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='context',
            field=models.TextField(blank=True, default='', max_length=3000, verbose_name='Контекст таблицы'),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='message',
            field=models.TextField(default='', max_length=600, verbose_name='Приложенное сообщение'),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='top_names',
            field=models.TextField(blank=True, default='', verbose_name='Имена столбцов'),
        ),
        migrations.AlterField(
            model_name='reportinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнего обновления'),
        ),
    ]
