# Generated by Django 2.2.13 on 2020-11-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='additional_field',
            field=models.IntegerField(default=0, verbose_name='Дополнительные поля'),
        ),
    ]
