# Generated by Django 2.2.13 on 2020-09-01 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0002_auto_20200901_1229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganisationOfReport',
            new_name='Organisation',
        ),
    ]
