# Generated by Django 2.2.13 on 2020-08-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0002_auto_20200827_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleuser',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
