# Generated by Django 2.2.13 on 2020-10-22 07:45

from django.db import migrations
import separatedvaluesfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0002_auto_20201022_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='context',
            field=separatedvaluesfield.models.SeparatedValuesField(max_length=3000, null=True, verbose_name='Содержание таблицы'),
        ),
    ]
