# Generated by Django 2.2.13 on 2020-09-01 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0003_auto_20200901_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименованеи группы отчётов')),
            ],
        ),
        migrations.AddField(
            model_name='reportinfo',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_application.GroupOfReports'),
        ),
    ]
