# Generated by Django 2.2.19 on 2021-04-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0004_auto_20210407_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupofreports',
            old_name='context',
            new_name='organisations',
        ),
    ]
