# Generated by Django 2.2.13 on 2020-09-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_application', '0004_auto_20200901_1352'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportInfo',
            new_name='Report',
        ),
    ]
